# Generated by Django 4.2.3 on 2023-07-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fota_firmware",
            name="firmware_size",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
